apiVersion: apps/v1
kind: Deployment
metadata:
  name: rolly-app
  labels:
    app: rolly-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rolly-app
  template:
    metadata:
      labels:
        app: rolly-app
    spec:
      containers:
      - name: rolly-app
        image: uchit8847/rolly-app  # Replace with your actual Docker image name
        ports:
        - containerPort: 80