apiVersion: v1
kind: Service
metadata:
  name: rolly-app
spec:
  type: NodePort  # Change to NodePort if using Minikube
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30000
  selector:
    app: rolly-app